name: Create Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        run: sudo apt-get install -y equivs

      - uses: actions/checkout@v3

      - name: Create package
        run: equivs-build texlive-full-no-bloat.cfg
      
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: *.deb
      