name: Create Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        run: sudo apt-get install -y equivs

      - uses: actions/checkout@v3

      - name: Create package
        run: equivs-build texlive-full-no-bloat.cfg
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.deb'
      